Vinicius layout
ifspcodelab/ifspcodelab.github.io pull request #2
Opened 2019-03-13 21:23 UTC by viniciusecortez

Feito o layout

2019-03-14 14:09 UTC, domingoslatorre requested changes

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +<html lang="en">
Alterar lang para pt-BR https://developer.mozilla.org/pt-BR/docs/Web/HTML/Global_attributes/lang
```html
<html lang="pt-BR">
```

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <!-- Required meta tags -->
Remove os comentários do template inicial do bootstrap.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <!-- Bootstrap CSS -->
Remove os comentários do template inicial do bootstrap.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +      <small style="display: block;">
Criar um arquivo CSS separado e remover as definições inline das linhas 19, 61, 69, 73, 81, 85.

Para linha 19:

```HTML
<a class="navbar-brand p-2" href="#">
   <small>IFSP</small>CODELAB
</a>
```

```CSS
.navbar-brand {
    font-weight: bold;
}
.navbar-brand small {
    display: block;
}
```

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +        <b>LAYOUT</b>
Este elemento representa o título da página, para ficar semanticamente correto utilizar o elemento h1.

```HTML
<h1>Layout</h1>
````
Você pode usar também text-tranform para forçar a renderização em letras maiúsculas.

```CSS
.titulo-pagina h1 {
   font-size: 20px;
   text-transform: uppercase;
}
````

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <div class="container-fluid" style="background-color:rgb(238,238,238); border-top:1px solid black ;border-bottom: 1px solid black; font-size:20px; ">
Para aplicar um estilo a um container/container-fluid defina uma classe no elemento HTML (no caso aqui ``titulo-pagina``) e coloque as definições de formatação no arquivo CSS.

```HTML
<div class="container-fluid titulo-pagina">
````

```CSS
.titulo-pagina {
    border-top: 1px solid black;
    border-bottom: 1px solid black; 
    background-color: rgb(238,238,238); 
}
````

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <div class="container" style="height:1000px">
A altura do ``container`` principal será definida pela altura dos elementos internos. Não precisa definir aqui no HTML.

```HTML
<div class="container">
```

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +    <div class="row p-4" style="background-color:rgb(238,238,238);">
Ajustar o HTML e CSS conforme explicações anteriores.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +        <p style="font-size: 15px">
Ajustar o HTML e CSS conforme explicações anteriores.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +        <button type="button" class="btn btn-secondary float-right" style="background-color:rgb(62,62,62);">Entre em contato</button>
Ajustar o HTML e CSS conforme explicações anteriores.

Neste contexto o usuário só pode executar uma ação, não existe ação secundária. Ver: https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150 

Utilizar a classe ``btn-primary``

```HTML 
<button type="button" class="btn btn-primary float-right">Entre em contato</button>
```

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +    <div class="row" style="background-color: rgb(62,62,62); height: 150px;">
Ajustar o HTML e CSS conforme explicações anteriores.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <!-- Optional JavaScript -->
Remover comentários do template inicial do bootstrap.

2019-03-14 14:09 UTC, domingoslatorre commented on pages/layout.html
> +  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
Remover comentários do template inicial do bootstrap.

2019-03-15 13:01 UTC, damorais requested changes
Além das mudanças que o Latorre mencionou, acho interessante colocar marcações com comentário indicando o bloco que deverá ser alterado entre páginas, para facilitar o trabalho nas outras páginas. Algo como:
`<div class='container'> <!--MIOLO --> Aqui entra o conteúdo / HTML <!-- MIOLO --> </div>`

2019-03-18 01:21 UTC, viniciusecortez commented
> Além das mudanças que o Latorre mencionou, acho interessante colocar marcações com comentário indicando o bloco que deverá ser alterado entre páginas, para facilitar o trabalho nas outras páginas. Algo como:
> `<div class='container'> <!--MIOLO --> Aqui entra o conteúdo / HTML <!-- MIOLO --> </div>`

Já feita a alteração

2019-03-19 10:33 UTC, domingoslatorre requested changes

2019-03-19 10:33 UTC, domingoslatorre commented on pages/layout.html
>      </div>
Essa instrução de fechamento está sobrando. Acho que após isso já podemos dar merge na master. Parabéns pelo trabalho!

2019-03-19 21:29 UTC, domingoslatorre commented
Boa :+1:

2019-03-19 21:30 UTC, merged