Pagina01
ifspcodelab/ifspcodelab.github.io pull request #4
Opened 2019-03-19 19:08 UTC by matheusreisl

2019-03-19 23:43 UTC, domingoslatorre commented
@matheusreisl @viniciusecortez @jeffersonss999 @thiagoxra 
Sempre que vocês abrirem um pull request, escreva na descrição um resumo do que foi realizado naquela branch/conjunto de commit.

2019-03-20 09:55 UTC, domingoslatorre requested changes

2019-03-20 09:55 UTC, domingoslatorre commented on pages/01.html
> +          <div class="col-md-12 p-4">
Legal o uso da classe utilitária p-4 para definir o padding. Existe uma discussão sobre o uso da abordagem com classes utilitárias: https://medium.com/@oieduardorabelo/css-classes-utilita%CC%81rias-e-separation-of-concerns-3e412d787399

2019-03-20 09:55 UTC, domingoslatorre commented on pages/01.html
> +        <div class="row formatacao">
Tente dar um nome mais significativo para esta classe(formatacao) ou você pode usar o elemento main no container que representa o conteúdo principal e formatar os elementos textuais h2, h3, p internos via seletor de descendente, sem a necessidade de criar a classe.  

https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/main
https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator

2019-03-20 09:55 UTC, domingoslatorre commented on pages/01.html
> +            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
Vamos passar estes textos para vocês.

2019-03-21 19:47 UTC, viniciusecortez commented on pages/01.html
> +        <div class="row formatacao">
Alterada a classe para o componente main

2019-03-21 19:47 UTC, viniciusecortez commented on pages/01.html
> +            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
ok

2019-03-21 19:49 UTC, matheusreisl commented on pages/01.html
> +          <div class="col-md-12 p-4">
Ciente!

2019-03-25 17:47 UTC, viniciusecortez commented
Professor, eu resolvi o conflito que era causado pela derivação incorreta da branch que causava a exclusão de arquivos. Agora é possível usar o merge sem apagar os arquivos.

2019-03-25 20:54 UTC, damorais approved these changes

2019-03-25 21:11 UTC, damorais reviewed
Renomear o layout.html para missao-visao-valores.html implica em perder o arquivo original de layout. O ideal é criar uma cópia do arquivo e renomear tal cópia, assim o arquivo original é preservado (ao menos enquanto a aplicação é desenvolvida).

Observe o menu de navegação: Não está apontando para a página correta.

2019-03-25 21:13 UTC, damorais requested changes
Renomear o layout.html para missao-visao-valores.html implica em perder o arquivo original de layout. O ideal é criar uma cópia do arquivo e renomear tal cópia, assim o arquivo original é preservado (ao menos enquanto a aplicação é desenvolvida).

Observe o menu de navegação: Não está apontando para a página correta.

2019-03-27 18:49 UTC, merged